### ISSUE TITLE
interface says "no items found for this genre" on all genres

### ISSUE THREAD

**Issue by pding001** [zooniverse/shakespeares_world#129]
Not sure if this is a bug -- more likely something that still needs to be loaded -- but whenever I click on the genre buttons, it SW comes back with a message saying "no items found for this genre." There should be items, though from the 21 images for the beta.
![image](https://cloud.githubusercontent.com/assets/14045319/10952567/6fea2456-8311-11e5-89e8-d14aa0acae43.png)

**Comment by VVH** [comment]
Hi @pding001, we have grouped all of items under 'literary works' and get started, because at the moment, if people pick a genre and transcribe a bit, when they hit 'next' they'll get an out of data message. It will say in the beta email that they should just click get started. Things will be properly organized by genre for launch.

**Comment by simoneduca** [comment]
@pding001 @VVH I will hide the genre list just for the beta, just to avoid any possible confusion. See issue #133 for progress on that.

**Comment by pding001** [comment]
This workaround of grouping all the images under "Literary Works" is okay for the beta, I guess (though it means we won't be able to test how the genres buttons work with users). When I look at the "Literary Works" genre, however, I only see 10 pages, not 21. Where are the other 11 for the beta? [I added with comment to Issue #133 as well].
