### ISSUE TITLE
Hide genre list for beta

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#133]

**Comment by pding001** [comment]
This workaround of grouping all the images under "Literary Works" is okay for the beta, I guess (though it means we won't be able to test how the genres buttons work with users). When I look at the "Literary Works" genre, however, I only see 10 pages, not 21. Where are the other 11 for the beta?
![image](https://cloud.githubusercontent.com/assets/14045319/10971169/e493af0e-83a0-11e5-839f-8ced539a91a3.png)

**Comment by VVH** [comment]
Hi Paul, I've decided that we need to reduce the subject set size in order to be sure we are getting enough classifications on each image. I thought I had emailed about this, but perhaps not? For now, the beta test will have only one selection option: 'get started'. Consider this issue closed/off the table for now.
