### ISSUE TITLE
Cannot delete or edit blue dots in Firefox

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#136]

**Comment by rogerhutchings** [comment]
Just tried this in FF 41.0.2, and I couldn't replicate it. The context menu does appear, albeit in the wrong place (up in the top left), and I could edit / delete dots.

I do remember making a change to the various click events to use the X/Y coords from the Hammer event, rather than the mouse, as they're polyfilled - that should fix it?

**Comment by VVH** [comment]
Seems to have cleared up.
