### ISSUE TITLE
Edge issue with $.find() on SVG elements

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#150]
`.getElementsByClassName error:
zoom = new Hammer(MarkingSurfaceFactory.svg.find(".pan-zoom")[0]);`

**Comment by shaunanoordin** [comment]
Technical Details of Error:
* In *IE* and *Edge*, jQuery's 2's *$.find()* does not work if the context item is an *SVG* element (in this case, MarkingSurfaceFactory.svg)
* This is due to $.find()'s reliance on the common getElementsByClass() function, which SVG elements in IE do not have. IE SVG elements instead use querySelectorAll().

Overview of Problem / Possible Solutions:
* Current issue is that there are multiple instances of someSVGelement.find() being used in the app.
* Option 1: (brute force) individually identify which of the ~50 instances of .find() in main.js need to be replaced with querySelectorAll().
* Option 2: Use the experimental jQuery 3.0, which has a documented fix of this issue.

References:
* jQuery team identifies existence of "Class Selector with SVGs in IE" problem, plus technical details: https://github.com/jquery/sizzle/issues/322
* jQuery team indicates that the fix has been implemented... in jQuery 3.0. https://github.com/jquery/jquery/issues/2415
* jQuery 3.0 available as alpha: http://blog.jquery.com/2015/07/13/jquery-3-0-and-jquery-compat-3-0-alpha-versions-released/

**Comment by simoneduca** [comment]
Closed via 562d838024e64e57f3f67b8e22d71f82388cc8cb
