### ISSUE TITLE
Add full length/static tutorial to guide. 

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#267]
@simoneduca this isn't urgent but I think it would help people produce the best data.

**Comment by simoneduca** [comment]
@VVH Instead of adding it to the guide, where it might get ignored, I'm thinking to put it as a link that opens in a new tab, on the first step of the tutorial modal. Saying something like 'Full tutorial' (please advise on wording). That way users won't fail to know that the resource is available should they wish to use it. What do you think?
