### ISSUE TITLE
error when doing npm start (node v7 npm v4)

### ISSUE THREAD

**Issue by luchopcerra** [zooniverse/shakespeares_world#320]
Hi, i'm having trouble by doing npm start 

Seems like something is wrong with socket.io inside Karma...

i 've try the Following:

- git clone git@github.com:zooniverse/shakespeares_world.git

- cd shakespeares_world

- npm install

- NODE_ENV=production

- npm start

-------------------------------------------------------------------------------------------------------------

![image](https://cloud.githubusercontent.com/assets/3791276/23224056/9fd0d860-f90b-11e6-9e7c-56739ac91d07.png)

**Comment by simoneduca** [comment]
Thanks for pointing this out. It looks like one of the packages (`gulp-karma`) is tied to a specific version of `karma` and that version runs a `socket.io` version that doesn't work in `node v7.x`.
Turns out that `gulp-karma` has been deprecated anyway and we should use `karma` directly anyway. Fix coming shortly.
