### ISSUE TITLE
Transcription viewer page

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#54]
Some form of 'printing' your work when you've transcribed as much as you want. SD to look into whether libraries he's worked with before are transferrable to Angular.

**Comment by simoneduca** [comment]
On pressing 'Next' the user is offered the option of seeing the transcription made on a subject, grouped by annotation type (text, graphic or marginalia). In order to sort annotations within a given type with an order that mimic the order the user saved them with, an option is to sort them given the coordinates of each annotation and take the average of coordinates. This assumes that the user moves across the page from top-left to bottom-right, which clearly may not always be the case.
